eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1125/eureka/
server:
  port: 8100
spring:
  application:
    name: service-b

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
hystrix:
  metrics:
    enabled: true